/*
*插入菜单数据
*/
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '10001', '10001', '商户管理', 'merchants', '1', null, null, '0', '0000000001', null, null, '1000', 'dashboard', null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20001', '20001', '系统设置', 'setting', '1', null, null, '0', '0000000010', null, null, '2000', 'setting', null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20011', '20011', '用户管理', 'customer', '1', null, null, '0', '0000000010', null, null, '2010', 'contacts', null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20014', '20014', '医生管理', 'doctor', '1', null, null, '0', '0000000010', null, null, '2013', 'idcard', null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20017', '20017', '订单管理', 'order', '1', null, null, '0', '0000000010', null, null, '2016', 'book', null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20019', '20019', '内容管理', 'content', '1', null, null, '0', '0000000010', null, null, '2018', 'profile', null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '10002', '10002', '商户创建与管理', 'list', '2', '10001', null, '0', '0000000001', null, null, '1001', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20002', '20002', '微信推送设定', 'wechat-push', '2', '20001', null, '0', '0000000010', null, null, '2001', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20003', '20003', '关联微信公众号', 'wechat-relation', '2', '20001', null, '0', '0000000010', null, null, '2002', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20004', '20004', '基础信息设置', 'merchants-basic', '2', '20001', null, '0', '0000000010', null, null, '2003', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20005', '20005', '基础数据设置', 'data', '2', '20001', null, '0', '0000000010', null, null, '2004', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20006', '20006', '报警管理', 'alert-manage', '2', '20001', null, '0', '0000000010', null, null, '2005', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20009', '20009', '账号管理', 'account', '2', '20001', null, '0', '0000000010', null, null, '2008', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20010', '20010', '医生墙数据设定', 'doctor-wall', '2', '20001', null, '0', '0000000010', null, null, '2009', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20012', '20012', '用户管理', 'users', '2', '20011', null, '0', '0000000010', null, null, '2011', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20013', '20013', '档案', 'record', '2', '20011', null, '0', '0000000010', null, null, '2012', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20015', '20015', '医生认证管理', 'list', '2', '20014', null, '0', '0000000010', null, null, '2014', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20016', '20016', '医生价格管理', 'price-manage', '2', '20014', null, '0', '0000000010', null, null, '2015', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20018', '20018', '订单管理', 'order', '2', '20017', null, '0', '0000000010', null, null, '2017', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20020', '20020', '门诊管理', 'outpatient', '2', '20019', null, '0', '0000000010', null, null, '2019', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20021', '20021', '医生建议管理', 'suggest', '2', '20019', null, '0', '0000000010', null, null, '2020', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20022', '20022', '分成比例设定', 'commission', '2', '20014', null, '0', '0000000010', null, null, '2021', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20023', '20023', '医生排班管理', 'schedule', '2', '20014', null, '0', '0000000010', null, null, '2007', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20007', '20007', '医生基础数据设置', 'doctor-config-manage', '3', '20005', null, '0', '0000000010', null, null, '2006', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20008', '20008', '医生技能数据设置', 'doctor-skill-manage', '3', '20005', null, '1', '0000000010', null, null, '2007', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20024', '20024', '医生技能管理', 'skill', '2', '20014', null, '0', '0000000010', null, null, '2022', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20025', '20025', '在线医生管理', 'doctor-online', '2', '20014', null, '0', '0000000010', null, null, '2023', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20026', '20026', '财务管理', 'finacial', '1', null, null, '0', '0000000010', null, null, '2024', 'bank', null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20027', '20027', '医生提现', 'withdrawals', '2', '20026', null, '0', '0000000010', null, null, '2025', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20028', '20028', '数据报表', 'da', '1', null, null, '0', '0000000010', null, null, '2026', 'table', null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20029', '20029', '听单时长导出', 'order-service', '2', '20028', null, '0', '0000000010', null, null, '2027', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20030', '20030', '追问管理', 'question', '2', '20019', null, '0', '0000000010', null, null, '2028', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20031', '20031', '疾病名称管理', 'disease', '2', '20001', null, '0', '0000000010', null, null, '2029', null, null, null, null);
//2018-05-22 00:51:29
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20032', '20032', '角色管理', 'role', '2', '20001', null, '0', '0000000010', null, null, '2030', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20033', '20033', '商品管理', 'goods', '1', null, null, '0', '0000000010', null, null, '2031', 'shop', null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20034', '20034', '服务项管理', 'service', '2', '20033', null, '0', '0000000010', null, null, '2031', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20035', '20035', '服务项管理', 'service-item', '3', '20034', null, '0', '0000000010', null, null, '2032', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20036', '20036', '操作项管理', 'operation-item', '3', '20034', null, '0', '0000000010', null, null, '2033', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20037', '20037', '商品规则管理', 'rule', '2', '20033', null, '0', '0000000010', null, null, '2034', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20038', '20038', '组合规则管理', 'compositing', '3', '20037', null, '0', '0000000010', null, null, '2035', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20039', '20039', '儿疾预约单管理', 'child-disease', '2', '20017', null, '0', '0000000010', null, null, '2036', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20040', '20040', '合约管理', 'contract', '1', null, null, '0', '0000000010', null, null, '2037', 'form', null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20041', '20041', '合约管理', 'manage', '2', '20040', null, '0', '0000000010', null, null, '2038', null, null, null, null);
insert into `yyxk`.`paas_function` ( `id`, `function_id`, `function_depict`, `function_path`, `function_level`, `parent_id`, `create_time`, `function_status`, `function_belong`, `keywords`, `function_depict_host`, `function_order`, `function_icon`, `operator`, `operator_id`, `operation_time`) values ( '20042', '20042', '合约检验报告管理', 'inspection-report', '2', '20019', null, '0', '0000000010', null, null, '2019', null, null, null, null);
/*
*插入用户菜单关联数据，需要传入
*/
insert into `yyxk`.`paas_user_function` ( `id`, `user_id`, `function_id`, `operator`, `operator_id`, `operation_time`) values (REPLACE(UUID(),'-',''), '用户ID', '菜单ID', 'yyxkAdmin', '000001', CURRENT_TIMESTAMP());
